config/routes.rb
Rails.application.routes.draw do
  resources :kaycies

  resources :biscuits

  resources :locations

  resources :categories

  resources :articles

end

app/controllers/kaycies_controller.rb
class KayciesController < ApplicationController
  before_action :set_kaycy, only: [:show, :edit, :update, :destroy]

  # GET /kaycies
  # GET /kaycies.json
  def index
    @kaycies = Kaycie.all
  end

  # GET /kaycies/1
  # GET /kaycies/1.json
  def show
  end

  # GET /kaycies/new
  def new
    @kaycy = Kaycie.new
  end

  # GET /kaycies/1/edit
  def edit
  end

  # POST /kaycies
  # POST /kaycies.json
  def create
    @kaycy = Kaycie.new(kaycy_params)

    respond_to do |format|
      if @kaycy.save
        format.html { redirect_to @kaycy, notice: 'Kaycie was successfully created.' }
        format.json { render :show, status: :created, location: @kaycy }
      else
        format.html { render :new }
        format.json { render json: @kaycy.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /kaycies/1
  # PATCH/PUT /kaycies/1.json
  def update
    respond_to do |format|
      if @kaycy.update(kaycy_params)
        format.html { redirect_to @kaycy, notice: 'Kaycie was successfully updated.' }
        format.json { render :show, status: :ok, location: @kaycy }
      else
        format.html { render :edit }
        format.json { render json: @kaycy.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /kaycies/1
  # DELETE /kaycies/1.json
  def destroy
    @kaycy.destroy
    respond_to do |format|
      format.html { redirect_to kaycies_url, notice: 'Kaycie was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_kaycy
      @kaycy = Kaycie.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def kaycy_params
      params.require(:kaycy).permit(:name, :content)
    end
end

app/helpers/kaycies_helper.rb
module KayciesHelper
end

app/views/kaycies/_form.html.erb
<%= form_for(@kaycy) do |f| %>
  <% if @kaycy.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@kaycy.errors.count, "error") %> prohibited this kaycy from being saved:</h2>

      <ul>
      <% @kaycy.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/kaycies/edit.html.erb
<h1>Editing kaycy</h1>

<%= render 'form' %>

<%= link_to 'Show', @kaycy %> |
<%= link_to 'Back', kaycies_path %>

app/views/kaycies/index.html.erb
<h1>Listing kaycies</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @kaycies.each do |kaycy| %>
      <tr>
        <td><%= kaycy.name %></td>
        <td><%= kaycy.content %></td>
        <td><%= link_to 'Show', kaycy %></td>
        <td><%= link_to 'Edit', edit_kaycy_path(kaycy) %></td>
        <td><%= link_to 'Destroy', kaycy, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Kaycie', new_kaycy_path %>

app/views/kaycies/new.html.erb
<h1>New kaycy</h1>

<%= render 'form' %>

<%= link_to 'Back', kaycies_path %>

app/views/kaycies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @kaycy.name %>
</p>

<p>
  <strong>Content:</strong>
  <%= @kaycy.content %>
</p>

<%= link_to 'Edit', edit_kaycy_path(@kaycy) %> |
<%= link_to 'Back', kaycies_path %>