config/routes.rb
Rails.application.routes.draw do
  resources :kaycies

  resources :biscuits

  resources :locations

  resources :categories

  resources :articles

end

app/models/biscuit.rb
class Biscuit < ActiveRecord::Base
end

app/controllers/biscuits_controller.rb
class BiscuitsController < ApplicationController
  before_action :set_biscuit, only: [:show, :edit, :update, :destroy]

  # GET /biscuits
  # GET /biscuits.json
  def index
    @biscuits = Biscuit.all
  end

  # GET /biscuits/1
  # GET /biscuits/1.json
  def show
  end

  # GET /biscuits/new
  def new
    @biscuit = Biscuit.new
  end

  # GET /biscuits/1/edit
  def edit
  end

  # POST /biscuits
  # POST /biscuits.json
  def create
    @biscuit = Biscuit.new(biscuit_params)

    respond_to do |format|
      if @biscuit.save
        format.html { redirect_to @biscuit, notice: 'Biscuit was successfully created.' }
        format.json { render :show, status: :created, location: @biscuit }
      else
        format.html { render :new }
        format.json { render json: @biscuit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /biscuits/1
  # PATCH/PUT /biscuits/1.json
  def update
    respond_to do |format|
      if @biscuit.update(biscuit_params)
        format.html { redirect_to @biscuit, notice: 'Biscuit was successfully updated.' }
        format.json { render :show, status: :ok, location: @biscuit }
      else
        format.html { render :edit }
        format.json { render json: @biscuit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /biscuits/1
  # DELETE /biscuits/1.json
  def destroy
    @biscuit.destroy
    respond_to do |format|
      format.html { redirect_to biscuits_url, notice: 'Biscuit was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_biscuit
      @biscuit = Biscuit.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def biscuit_params
      params.require(:biscuit).permit(:name, :content)
    end
end

app/helpers/biscuits_helper.rb
module BiscuitsHelper
end

app/views/biscuits/_form.html.erb
<%= form_for(@biscuit) do |f| %>
  <% if @biscuit.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@biscuit.errors.count, "error") %> prohibited this biscuit from being saved:</h2>

      <ul>
      <% @biscuit.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/biscuits/edit.html.erb
<h1>Editing biscuit</h1>

<%= render 'form' %>

<%= link_to 'Show', @biscuit %> |
<%= link_to 'Back', biscuits_path %>

app/views/biscuits/index.html.erb
<h1>Listing biscuits</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @biscuits.each do |biscuit| %>
      <tr>
        <td><%= biscuit.name %></td>
        <td><%= biscuit.content %></td>
        <td><%= link_to 'Show', biscuit %></td>
        <td><%= link_to 'Edit', edit_biscuit_path(biscuit) %></td>
        <td><%= link_to 'Destroy', biscuit, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Biscuit', new_biscuit_path %>

app/views/biscuits/new.html.erb
<h1>New biscuit</h1>

<%= render 'form' %>

<%= link_to 'Back', biscuits_path %>

app/views/biscuits/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @biscuit.name %>
</p>

<p>
  <strong>Content:</strong>
  <%= @biscuit.content %>
</p>

<%= link_to 'Edit', edit_biscuit_path(@biscuit) %> |
<%= link_to 'Back', biscuits_path %>